server.port=8080
server.servlet.context-path=/api/1.0
spring.datasource.url=jdbc:mysql://localhost:3306/harpia

spring.datasource.username=testuser
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
